import TrieSearch from "trie-search";

export const countryData = [
    "Greenland",
    "El Salvador",
    "Georgia",
    "Guyana",
    "Montenegro",
    "Greece",
    "Botswana",
    "Sri Lanka",
    "Oman",
    "Lithuania",
    "Maldives",
    "Portugal",
    "Samoa",
    "Sierra Leone",
    "Brunei",
    "British Virgin Islands",
    "Jamaica",
    "Northern Mariana Islands",
    "San Marino",
    "Malawi",
    "Malaysia",
    "American Samoa",
    "Chad",
    "Taiwan",
    "Anguilla",
    "Antigua and Barbuda",
    "Djibouti",
    "Christmas Island",
    "Ireland",
    "Cuba",
    "Mauritius",
    "Bulgaria",
    "Guadeloupe",
    "Guinea-Bissau",
    "Egypt",
    "Martinique",
    "Bahamas",
    "Germany",
    "Libya",
    "Argentina",
    "Venezuela",
    "South Sudan",
    "Comoros",
    "Bosnia and Herzegovina",
    "Niger",
    "Nicaragua",
    "Zambia",
    "Saint Barthélemy",
    "Dominica",
    "Guinea",
    "DR Congo",
    "French Guiana",
    "Saudi Arabia",
    "Central African Republic",
    "Andorra",
    "Saint Vincent and the Grenadines",
    "Estonia",
    "Faroe Islands",
    "Vatican City",
    "Austria",
    "Colombia",
    "Senegal",
    "Singapore",
    "Laos",
    "Cayman Islands",
    "Eswatini",
    "Sudan",
    "Tuvalu",
    "Syria",
    "United States Minor Outlying Islands",
    "Liberia",
    "Marshall Islands",
    "Switzerland",
    "Iceland",
    "Turks and Caicos Islands",
    "Zimbabwe",
    "Brazil",
    "Rwanda",
    "Liechtenstein",
    "Uzbekistan",
    "Wallis and Futuna",
    "Slovakia",
    "Montserrat",
    "United States",
    "Bangladesh",
    "Gibraltar",
    "Aruba",
    "Panama",
    "Philippines",
    "Ecuador",
    "Russia",
    "Mozambique",
    "Saint Helena, Ascension and Tristan da Cunha",
    "Iran",
    "Canada",
    "Afghanistan",
    "Spain",
    "Grenada",
    "Mayotte",
    "Falkland Islands",
    "Romania",
    "Azerbaijan",
    "Guernsey",
    "Cambodia",
    "Suriname",
    "Bouvet Island",
    "Algeria",
    "Armenia",
    "French Southern and Antarctic Lands",
    "Morocco",
    "Barbados",
    "Angola",
    "Solomon Islands",
    "Mali",
    "New Caledonia",
    "Belgium",
    "Fiji",
    "Latvia",
    "Mexico",
    "Macau",
    "Bahrain",
    "Yemen",
    "Caribbean Netherlands",
    "United States Virgin Islands",
    "Mauritania",
    "Cook Islands",
    "Monaco",
    "Niue",
    "Peru",
    "British Indian Ocean Territory",
    "Serbia",
    "Tanzania",
    "Pakistan",
    "Belarus",
    "Saint Lucia",
    "Puerto Rico",
    "Myanmar",
    "Seychelles",
    "Bermuda",
    "Ukraine",
    "Gambia",
    "Paraguay",
    "São Tomé and Príncipe",
    "Denmark",
    "South Korea",
    "Saint Pierre and Miquelon",
    "Tunisia",
    "Kuwait",
    "Italy",
    "South Georgia",
    "Åland Islands",
    "Cyprus",
    "Luxembourg",
    "Papua New Guinea",
    "Togo",
    "Hong Kong",
    "Kiribati",
    "Madagascar",
    "United Kingdom",
    "Bolivia",
    "Isle of Man",
    "Slovenia",
    "Réunion",
    "Kyrgyzstan",
    "New Zealand",
    "Kazakhstan",
    "North Macedonia",
    "Heard Island and McDonald Islands",
    "Tonga",
    "Kosovo",
    "Chile",
    "Burundi",
    "Dominican Republic",
    "Western Sahara",
    "Lesotho",
    "North Korea",
    "Cocos (Keeling) Islands",
    "Bhutan",
    "Somalia",
    "Netherlands",
    "Tajikistan",
    "Timor-Leste",
    "Lebanon",
    "Sint Maarten",
    "Uganda",
    "Ghana",
    "Albania",
    "Palau",
    "Micronesia",
    "Curaçao",
    "Finland",
    "Jersey",
    "Namibia",
    "Vietnam",
    "Antarctica",
    "Palestine",
    "Turkey",
    "Moldova",
    "Saint Kitts and Nevis",
    "Australia",
    "Japan",
    "Croatia",
    "Burkina Faso",
    "Indonesia",
    "Turkmenistan",
    "Republic of the Congo",
    "Vanuatu",
    "Belize",
    "Ethiopia",
    "Honduras",
    "Poland",
    "Nauru",
    "Norfolk Island",
    "Qatar",
    "Haiti",
    "Uruguay",
    "Kenya",
    "Equatorial Guinea",
    "Benin",
    "France",
    "Thailand",
    "Guam",
    "Saint Martin",
    "India",
    "Jordan",
    "Costa Rica",
    "Nepal",
    "Cape Verde",
    "Trinidad and Tobago",
    "South Africa",
    "Gabon",
    "Eritrea",
    "Israel",
    "Nigeria",
    "Norway",
    "French Polynesia",
    "Sweden",
    "Iraq",
    "Pitcairn Islands",
    "Tokelau",
    "Cameroon",
    "China",
    "United Arab Emirates",
    "Ivory Coast",
    "Malta",
    "Mongolia",
    "Guatemala",
    "Czechia",
    "Hungary",
    "Svalbard and Jan Mayen",
];

export const trie = new TrieSearch(null, { ignoreCase: true });

// Setup trie
for (const x of countryData) {
    trie.map(x, x);
}

/*
@param {string} searchStr
@return {string[]} 
*/
export const search = (searchStr) => {
    return trie.search(searchStr);
};
